### ISSUE TITLE
except localhost, nothing else is working

### ISSUE THREAD

**Issue by changemenemo** [magnetikonline/dockerhtml5validator#8] opened 2016-11-11 13:48 UTC
hi,

except localhost, it's not working because your apacheserver is always resend result in localhost. 
So I know that you certainly only want the usecase of a docker engine installed on the localmachine where you are working out but there are a lot more usecase;
For example, you can imagine someone working on a tablet or a phone to rapidly make changes to an html file and he want to test it. So because of your one usecase, he will have to connect to the online website to validate the modification he just did.
Other usercase, every windows computer doesn't allow to use docker because of the CPU which has not vt-x etc. ... And sometimes you don't have internet but just your intranet so it could be great if you could change it to make it work on 0.0.0.0 and not only localhost? if it is possible. If I had the time right now I would gladly do it myself but I will have to wat a few more weeks if I have to do it myself and it would be great if I could use it right now....

**Comment by magnetikonline** [comment] 2016-11-12 04:03
Thanks for the issue post @boistordu - but I'm not quite sure I understand the problem here?

Since you're in a Docker container runtime listening on `0.0.0.0` won't help - as you still need to `--publish` the port back to the host with `docker run`. 

Can you maybe provide a screenshot of what the issue is to help explain?

**Comment by boistordu** [comment] 2016-11-12 16:54
well if I try the tool, when I entered something it will return to me a localhost address so not the adress of the server.... SO of course i would have a 404 error
nothing about ports here....

**Comment by magnetikonline** [comment] 2016-11-13 04:57
Yeah I'm still not understanding. I just re-built the image from `Dockerfile` to check.

- Run the image via `./run.sh`
- Visit `http://127.0.0.1:8080/` on host.
- Enter a URL - either local to your network or public internet. Local URL's will need to be resolvable via the container, so either a local DNS server in your network, or you might need to pass your `/etc/hosts` entries into the container at run time.
- Page is validated.

I guess we might have a communication breakdown here?

**Comment by boistordu** [comment] 2016-11-13 09:35
if you want to understand better I can pm you the adres and you can test by yourself

**Comment by boistordu** [comment] 2016-11-13 09:39
there are no interface on the host. the run command was 'docker run --restart=always --network=accessed --name valid -p 45116:80 -p 45117:8080 -d magnetikonline/html5validator` and so obviously it's no different as your run.

**Comment by magnetikonline** [comment] 2016-11-15 23:11
So after that run line - if you visit `http://127.0.01:45116/` what do you get?

**Comment by backflip** [comment] 2016-11-29 23:14
@magnetikonline, do you have an idea how I'd deploy this with [now.sh](https://zeit.co/now/)? I can start it by simply running `now`, however, the form will redirect to `localhost` when submitting: https://dockerhtml5validator-azybyqnlkf.now.sh. Same issue with `now -p 8080:80 -p 8888:8888`.

**Comment by boistordu** [comment] 2016-11-30 11:34
@magnetikonline sorry for the delay of answer. 
127.0.0.1 did you understand that it was on a local VPS my installation right? The goal is to not having it on localhost no 127.0.0.1 then....  so if I upload a file from remote host it will put the following adress: http://localhost:8888/html5/#file

for bug debugging purposes, I've installed docker on one of the workstation and as @backflip have said, your html code is redirecting to localhost:8888 which is unusable for docker of course! You have to use environment variable or something else to retain the port redirection and your code html have to point it with this variable.

**Comment by backflip** [comment] 2016-12-04 16:45
It would probably make sense to use a single port instead of two (now.sh does not expose multiple ports, e.g., https://github.com/zeit/now/issues/149#issuecomment-264240143).

**Comment by magnetikonline** [comment] 2016-12-04 21:42
@boistordu right, so finally I understand what you're saying now.

(For others reading):
- When submitting HTML to the validator, if the source is HTML5 the validator _replays_ the validation against the HTML5 VNU validator.
- Currently the setup here is hardcoded to that endpoint being `localhost:8888/html5`, which is fine locally, but if you were to install this publicly or listening on an alternative domain a redirection/replay to `localhost:8888` isn't going to help you. 

As you say, will probably need to solve this with an environment variable as the environment itself can't possibly work this hostname out itself, also:
- Will probably need to avoid calling `supervisord` direct from `Dockerfile` - instead call a bash script that adjusts `/etc/w3c/validator.conf` with a given environment variable which is your desired public hostname. This could be baked into `run.sh` as an argument as well.
- The adjustment would be to here before running Apache/HTML5 validator parts via `supervisord` https://github.com/w3c/markup-validator/blob/master/htdocs/config/validator.conf#L128.

I think I have given you the steps you need to solve this - so go at it! I might tackle this in the future if time allows, but for me personally - it's low use.

Thanks.

**Comment by magnetikonline** [comment] 2016-12-04 21:44
@backflip seems your issue is very much related. Yeah I don't have a fix for now - short of hacking this:

https://github.com/magnetikonline/dockerhtml5validator/blob/master/resource/configure.sh#L82-L85

But that's not very flexible - so injecting a hostname/port via `run.sh` into the container which is then used to modify `validator.conf` before running services, would serve this better.

**Comment by magnetikonline** [comment] 2016-12-04 21:45
I'll close this for now, as mentioned if I feel inspired I'll try to write an enhancement.

**Closed as completed by magnetikonline** 2016-12-04 21:45 UTC
Labels: help wanted

**Comment by backflip** [comment] 2016-12-04 23:26
Hey @magnetikonline, I decided on [exposing](https://github.com/magnetikonline/dockerhtml5validator/blob/master/Dockerfile#L21) 8888 instead of 80 since I need the HTML5 validator only. Works like a charm.

**Comment by magnetikonline** [comment] 2016-12-04 23:33
@backflip nice one.... yep, that would do the trick 💃

**Comment by boistordu** [comment] 2016-12-05 09:31
May I ask you why you download the old validator too in place of just the new one? Since it is standalone with a webui

**Comment by boistordu** [comment] 2016-12-05 11:11
Okey so the vnu is working as expected in standalone. This is your combination with something which is not maintained anymore which cause the problem: https://github.com/w3c/markup-validator/issues/17
