### ISSUE TITLE
Sometimes results deviate from the live W3C Validator

### ISSUE THREAD

**Issue by avikshee** [magnetikonline/dockerhtml5validator#4] opened 2015-03-09 10:41 UTC
Hello,

Thanks a ton for this great self contained W3C Markup validator. I had been checking the results after building this container, but the results sometimes vary from the live W3C Validator (http://validator.w3.org/).

These are the names of some sites for which you would see that the results deviate from the hosted one:

grantwatch.com
merruk.com
tarnegarco.com

It would be helpful if the validator container can be updated and it can be made to return results similar to the live one to avoid ambiguity. Thought this info would be of some help to you and thanks once more for this great repo.

Thanks,
Avik

**Comment by magnetikonline** [comment] 2015-03-09 22:56
Hello @avikshee - thanks for the issue and kind words.

Are you able to provide a summary of where the issues/vary? I'm assuming it's because the HTML5 validation engine that I'm using here (the excellent [vnu validator](https://github.com/validator/validator/releases)) is not what is being used at http://validator.w3.org/.

If can provide some examples (text is fine - here) - I'll see if I can reproduce.

**Comment by avikshee** [comment] 2015-03-10 09:24
Hello,

Thanks for replying back. I too assumed that the results vary as the HTML5 validation engine used here might be different from the one that is being used by validator.w3.org.

Here's are a few examples:

Test case 1:
Evaluation of www.merruk.com
---------------------------------------

Live validator:
http://validator.w3.org/check?uri=http%3A%2F%2Fwww.merruk.com
Passed, 1 warning(s)

Hosted Validator:
13 Errors, 1 warning(s)

  Line 7, Column 926: A charset attribute on a meta element found after the first 512 bytes.
  Line 12, Column 1260: Attribute datatype not allowed on element meta at this point.
  Line 12, Column 1352: Attribute datatype not allowed on element meta at this point.
  Line 12, Column 1498: Attribute datatype not allowed on element meta at this point.
  Line 12, Column 1724: Attribute datatype not allowed on element meta at this point.
  Line 12, Column 2140: Bad value dcterms:subject for attribute rel on element link: The string dcterms:subject is not a registered keyword.
  Line 12, Column 2196: Bad value dc:source for attribute rel on element link: The string dc:source is not a registered keyword.
  Line 12, Column 2250: Bad value dc:relation for attribute rel on element link: The string dc:relation is not a registered keyword.
  Line 12, Column 2323: Bad value dcterms:references for attribute rel on element link: The string dcterms:references is not a registered keyword.
  Line 13, Column 2184: Bad value version for attribute name on element meta: Keyword version is not registered.


Test case 2:
Evaluation of www.grantwatch.com
--------------------------------------------

Live Validator:
http://validator.w3.org/check?uri=grantwatch.com
Passed, 2 warning(s)

Hosted Validator:
1 Error, 2 warning(s)

Line 11, Column 55: Bad value X-UA-Compatible for attribute http-equiv on element meta.
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

I can provide you with more test cases, if you need.
Thanks once more for following up on this.

Thanks,
Avik

**Comment by jaimeiniesta** [comment] 2015-03-10 12:20
I've tried this and I can confirm that I get the same results as @avikshee 

I've noticed that on the Dockerfile, the [sgml-lib](https://github.com/magnetikonline/dockerhtml5validator/blob/master/Dockerfile#L16) file that is being used is not the most up-to-date one.

[This guide](https://github.com/tlvince/w3c-validator-guide#2-install-validator) explains how to use a more recent sgml-lib file.

Please note however that the [W3C Validator is legacy](http://sitevalidator.com/blog/2015/03/w3c-validator-is-legacy-long-live-validator-nu/). It's not actively maintained, you should instead be using http://validator.w3.org/nu/

You can install the Nu HTML Checker without installing the legacy validator. Here's a [Dockerfile](https://github.com/sitevalidator/validator-nu-docker/tree/release_2015_02_16) for it.

**Comment by magnetikonline** [comment] 2015-03-10 22:28
Thanks @avikshee @jaimeiniesta for the replies.

Given time, I try building with this updated sgml-lib release - see if that corrects the issue? Still, I was under the impression the W3 validator handed off the HTML body wholesale to the VNU/NU validator so I'm not sure if this will fix the issue. Would love to know where live W3 validator drifts away from what I am building here.

Main reason @jaimeiniesta I'm sticking with the W3 validator - allows me to use the excellent [Validity](https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif?hl=en-GB) Chrome extension.

**Comment by magnetikonline** [comment] 2015-08-08 17:03
Hello @avikshee,

  *finally* found some time to look into this - since we last looked at this issue, quite a bit has changed with the W3C validator (for the better!):

- The W3C validator source is now hosted on GitHub at https://github.com/w3c/markup-validator - rather than in tar files on their servers. In fact, these files no longer exist - meaning that this Dockerfile has been broken for a little while!
- The Validator.nu checker is now called directly by the W3C validator at https://validator.w3.org/ - that is, if your "site to validate" is HTML5/etc. the W3C validator will simply redirect you to the Validator.nu instance they are running.
- The Validator.nu JAR itself has had quite a few source version bumps/fixes since my last update.

So - I have updated this repo to reflect these changes with a rather large commit/update: https://github.com/magnetikonline/dockerhtml5validator/commit/5334c970066fe47f5630b5c0693fe54ef161e187.

Thought I should outline all this in greater detail - in the case that someone else finds this information of use.

I'm going to close this issue out - as you should now find (at least for now) - results from this Dockerfile should be pretty much spot-on with that of the live https://validator.w3.org/.

**Closed by magnetikonline** 2015-08-08 17:03 UTC
Labels: bug, question
